USE MASTER
GO
CREATE DATABASE DONGHO
GO	
USE DONGHO
GO
CREATE TABLE HANGSX(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENHSX NVARCHAR(100),
	DIACHI NVARCHAR(200),
	THONGTIN NVARCHAR(500),
	WEBSITE NVARCHAR(50)
)
Go
CREATE TABLE DANHMUC(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDM NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE SANPHAM(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(100),
	SOLUONG INT,
	DONGIA INT,
	XUATXU NVARCHAR(30),
	BAOHANH NVARCHAR(20),
	KIEUDANG NVARCHAR(100),
	NANGLUONG NVARCHAR(50),
	DUONGKINHMAT NVARCHAR(20),
	HINHANH NVARCHAR(1000),
	IDHANGSX INT NOT NULL,
	IDDANHMUC INT NOT NULL,
	FOREIGN KEY (IDHANGSX) REFERENCES dbo.HANGSX(ID),
	FOREIGN KEY (IDDANHMUC) REFERENCES dbo.DANHMUC(ID),
)
GO
CREATE TABLE DONHANG(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NGUOINHAN NVARCHAR(30) NOT NULL,
	SDT INT NOT NULL,
	DIACHI NVARCHAR(200) NOT NULL,
	EMAIL NVARCHAR(50),
	TONGTIEN INT NOT NULL,
	IDTK INT,
	FOREIGN KEY (IDTK) REFERENCES dbo.TAIKHOAN(ID)
)
GO
CREATE TABLE CHITIETDONHANG(
	IDDONHANG INT NOT NULL,
	IDSANPHAM INT NOT NULL,
	SOLUONG INT NOT NULL,
	FOREIGN KEY (IDDONHANG) REFERENCES dbo.DONHANG(ID),
	FOREIGN KEY (IDSANPHAM) REFERENCES dbo.SANPHAM(ID)
)

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDONHANG](
	[MaDH] [int]  NOT NULL,
	[MaSP] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDH] ASC,
	[MaSP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [dbo].[CHITIETDONHANG]  WITH CHECK ADD  CONSTRAINT [FK__CHITIETDON__MaDH__145C0A3F] FOREIGN KEY([MaDH])
REFERENCES [dbo].[DONHANG] ([ID])
GO
ALTER TABLE [dbo].[CHITIETDONHANG] CHECK CONSTRAINT [FK__CHITIETDON__MaDH__145C0A3F]
GO
ALTER TABLE [dbo].[CHITIETDONHANG]  WITH CHECK ADD  CONSTRAINT [FK__CHITIETDON__MaSP__15502E78] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([ID])
GO
ALTER TABLE [dbo].[CHITIETDONHANG] CHECK CONSTRAINT [FK__CHITIETDON__MaSP__15502E78]
GO


GO
CREATE TABLE TAIKHOAN(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
	TAIKHOAN CHAR(15),
	MATKHAU CHAR(15),
	HOTEN NVARCHAR(30),
	SDT INT,
	DIACHI NVARCHAR(200),
	GMAIL NVARCHAR(50),
	QUYEN NVARCHAR(20)
)
GO
CREATE TABLE GOPYHOIDAP(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(30),
	SDT INT,
	DIACHI NVARCHAR(200),
	GMAIL NVARCHAR(50),
	NOIDUNG NVARCHAR(4000),
	IDTK INT,
	FOREIGN KEY (IDTK) REFERENCES dbo.TAIKHOAN(ID)
)
go
create proc [dbo].[insert2] (@tentk nvarchar(15), @matkhau nvarchar(15), @tenkh nvarchar(30), @sdt int, @diachi nvarchar(200),@gmail nvarchar(50),@quyen nvarchar(20))
as
begin
	if(not exists (select * from TAIKHOAN where  TAIKHOAN.TAIKHOAN=@tentk))
	begin
		insert into TAIKHOAN values (@tentk,@matkhau,@tenkh,@sdt,@diachi,@sdt,@gmail,@quyen)
	end		
end

CREATE PROCEDURE [dbo].[ThemTaiKhoan]
@TENTK NVARCHAR(15), 
@MATKHAU NVARCHAR(15),
@TENKH NVARCHAR(30),
@SDT INT,
@DIACHI NVARCHAR(200),
@GMAIL NVARCHAR(50),
@QUYEN NVARCHAR(20)
AS
	BEGIN
		IF(NOT EXISTS (SELECT * FROM TAIKHOAN WHERE  TAIKHOAN.TAIKHOAN=@TENTK))
	BEGIN
		INSERT INTO TAIKHOAN VALUES(@TENTK,@MATKHAU,@TENKH,@SDT,@DIACHI,@GMAIL,@QUYEN)
	END
END